### ISSUE TITLE
How to generate the input file from genome.fna

### ISSUE THREAD

**Issue by MrTomRod** [petercim/ClusterFinder#1]
Could you briefly explain which tools to use to generate the input file?
GLIMMER and HMMER?

**Comment by petercim** [comment]
Hi, 
That would depend on your starting point. Are you starting from nucleotide sequences or protein sequences? If former, are those assembled genomes or raw reads from sequencer machines?

Best,
Peter

**Comment by MrTomRod** [comment]
Thank you for your response.
I have assembled nucleotide sequences.
(Read trimmed, SPades de novo assembled. Scaffolds with low coverage discarded. Median number of scaffolds: 81.)
(Also, I have [Prokka](https://github.com/tseemann/prokka)-Output files. These contain some pfam-related information, but not everything that is needed for ClusterFinder I think.)

**EDIT:** Here the heads of some of the Prokka files: https://pastebin.com/3WyekXJN

**Comment by petercim** [comment]
Yes, in that case glimmer and hmmer would be a good start. There may be other methods that came to market in the last couple of years since I've stopped being more deeply engaged in the field, so you may wanna check that. Also, ClusterFinder is integrated into AntiSMASH ([link](https://antismash.secondarymetabolites.org/#!/start)), which might be able to take nt sequences as inputs as well.

Thanks for your interest in using ClusterFinder, and sorry for not having more concrete answers.

Best,
Peter
